export const COLORS = {
  PRIMARY_BACKGROUND: '#76dafe',
  PRIMARY_FOREGOUND: '#3c6c82',
  PRIMARY_TEXT_COLOR: '#f7feff',
  WHITE:"#fff",
  CORRECT_ANSWER_BACKGROUND:"#08e1e6",
  WRONG_ANSWER_BACKGROUND:"#ff8e8a",
  SHADOW_BACKGROUND:"#6392a6"
};
